### PR TITLE
Pivotted the layout of this repo

### PR DESCRIPTION
**Pull request by JonTheNiceGuy**
* Moved test-* to tests/
* Moved library/* to /
* Created Examples to put the openrc.example and ansible.cfg into

### CODE REVIEW

**Comment by mohclips** [comment]
I like the idea of tidying this up, but the thing about doing it this way is that the tests do not run.   As the library/ folder is missing.  I'm currently unsure on how on how to go about it.

How are you running the tests?  what sort of setup is required before being able to use the modules, the tests and the examples?

**Comment by JonTheNiceGuy** [comment]
Oops, forgot to run the tests. D'oh I'll fix that tomorrow!

**Comment by mohclips** [comment]
We have a conflict now.   
Conflicting files
library/k5_create_port.py

Ill need to look at why.

**Comment by JonTheNiceGuy** [comment]
I need to pull from your master and then push it back in. Give me 10 mins, I'll sort it.

**Comment by JonTheNiceGuy** [comment]
OK, that was easier than I thought!! `git merge master` :)

**Pull request merged**
